version: '3'
services:
  lambda-layer:
    image: amazon/aws-sam-cli-build-image-python3.9:latest
    container_name: lambda-layer
    volumes:
      - ../../:/app
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID_TF}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY_TF}
      - SECRET_PATH=${SECRET_PATH}
      - RESOURCE_DIR=${RESOURCE_DIR}
    working_dir: /app
    tty: true