version: '3'
services:
  terraform:
    image: hashicorp/terraform:latest
    container_name: terraform
    volumes:
      - ../../../:/app
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID_TF}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY_TF}
      - SECRET_PATH=${SECRET_PATH}
      - RESOURCE_DIR=${RESOURCE_DIR}
    working_dir: /app
    tty: true
    entrypoint: /bin/sh