version: '3'
services:
  terraform:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: terraform
    volumes:
      - ..:/app
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=ap-northeast-1
    working_dir: /app
    tty: true
    entrypoint: /bin/sh
    command: -c "/bin/sh"
